# Project
build_number=450
group=vazkii.botania
java_version=25

# Minecraft / NeoForge
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)
mod_name=Botania
mod_author=Vazkii
mod_id=botania
license=Botania license
mod_version=1.0.0

# Mappings
parchment_minecraft=26.2
parchment_version=2025.11.17

# Dependencies
patchouli_version=26.1-94
curios_version=15.0.0-beta.2

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
